[2023-01-04T12:52:06.624+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ticker_to_txt.save_ticker_list_to_txt scheduled__2023-01-03T09:00:00+00:00 [queued]>
[2023-01-04T12:52:06.631+0000] {taskinstance.py:1087} INFO - Dependencies all met for <TaskInstance: ticker_to_txt.save_ticker_list_to_txt scheduled__2023-01-03T09:00:00+00:00 [queued]>
[2023-01-04T12:52:06.631+0000] {taskinstance.py:1283} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T12:52:06.631+0000] {taskinstance.py:1284} INFO - Starting attempt 1 of 1
[2023-01-04T12:52:06.631+0000] {taskinstance.py:1285} INFO - 
--------------------------------------------------------------------------------
[2023-01-04T12:52:06.742+0000] {taskinstance.py:1304} INFO - Executing <Task(BashOperator): save_ticker_list_to_txt> on 2023-01-03 09:00:00+00:00
[2023-01-04T12:52:06.745+0000] {standard_task_runner.py:55} INFO - Started process 126 to run task
[2023-01-04T12:52:06.749+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'ticker_to_txt', 'save_ticker_list_to_txt', 'scheduled__2023-01-03T09:00:00+00:00', '--job-id', '180', '--raw', '--subdir', 'DAGS_FOLDER/ticker.py', '--cfg-path', '/tmp/tmpx1zmcb9h']
[2023-01-04T12:52:06.749+0000] {standard_task_runner.py:83} INFO - Job 180: Subtask save_ticker_list_to_txt
[2023-01-04T12:52:06.920+0000] {task_command.py:389} INFO - Running <TaskInstance: ticker_to_txt.save_ticker_list_to_txt scheduled__2023-01-03T09:00:00+00:00 [running]> on host a247bc2e8348
[2023-01-04T12:52:07.945+0000] {taskinstance.py:1513} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=ticker_to_txt
AIRFLOW_CTX_TASK_ID=save_ticker_list_to_txt
AIRFLOW_CTX_EXECUTION_DATE=2023-01-03T09:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2023-01-03T09:00:00+00:00
[2023-01-04T12:52:07.946+0000] {subprocess.py:63} INFO - Tmp dir root location: 
 /tmp
[2023-01-04T12:52:07.946+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'python script/python/ticker_to_txt.py']
[2023-01-04T12:52:07.956+0000] {subprocess.py:86} INFO - Output:
[2023-01-04T12:52:08.035+0000] {subprocess.py:93} INFO - python: can't open file 'script/python/ticker_to_txt.py': [Errno 2] No such file or directory
[2023-01-04T12:52:08.037+0000] {subprocess.py:97} INFO - Command exited with return code 2
[2023-01-04T12:52:08.047+0000] {taskinstance.py:1772} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.7/site-packages/airflow/operators/bash.py", line 197, in execute
    f"Bash command failed. The command returned a non-zero exit code {result.exit_code}."
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 2.
[2023-01-04T12:52:08.050+0000] {taskinstance.py:1327} INFO - Marking task as FAILED. dag_id=ticker_to_txt, task_id=save_ticker_list_to_txt, execution_date=20230103T090000, start_date=20230104T125206, end_date=20230104T125208
[2023-01-04T12:52:08.487+0000] {standard_task_runner.py:105} ERROR - Failed to execute job 180 for task save_ticker_list_to_txt (Bash command failed. The command returned a non-zero exit code 2.; 126)
[2023-01-04T12:52:08.524+0000] {local_task_job.py:159} INFO - Task exited with return code 1
[2023-01-04T12:52:08.544+0000] {taskinstance.py:2582} INFO - 0 downstream tasks scheduled from follow-on schedule check
